version: 0.6.1-dev3-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - pi-lighting
skip_branch_with_pr: true
configuration: Release
platform: x64

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

before_build:
- cmd: >-
    Get-Content -Path "Project-Aurora\Project-Aurora\Properties\AssemblyInfo.cs"
    
    git submodule update --init --recursive
    
    cd Project-Aurora
    
    nuget restore

assembly_info:
  patch: true
  file: Project-Aurora\Project-Aurora\Properties\AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)

build:
  project: Project-Aurora\Project-Aurora.sln
  verbosity: minimal

artifacts:
  - path: Build\Release
    name: Aurora-v$(appveyor_build_version)
    type: zip
    
deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: BawzLen0V83DjFE11VqpdO3eDPMDDsrWTaQsswrLcKcn2DF/hviRKkdTbGOX6kSL
  artifact: Build\Aurora-v$(appveyor_build_version).zip          
  draft: true
  prerelease: false
  on:
    branch: dev
    appveyor_repo_tag: true