name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not seen any activity in 90 days and has been flagged as stale. This issue will be closed in 2 weeks.'
        stale-pr-message: 'This pull request has not seen any activity in 90 days and has been flagged as stale. This pull request will be closed in 2 weeks.'
        stale-issue-label: 'Status: Stale'
        stale-pr-label: 'Status: Stale'
        exempt-pr-label: 'Never stale'
        exempt-issue-label: 'Never stale'
        days-before-stale: 90
        days-before-close: 14
        
        operations-per-run: 250
